language: node_js
node_js:
- '6'
branches:
  only:
  - master
notifications:
  slack:
    secure: IoCySZIcl2m64cS3AkQZ4DZ73tYf/I49jAgSE0defmyTakyphJOQN9WMP+Sg10pMITu+NGLYlq40EGgvHJW2E/GBA9w2H5R2kNGFi93yS+ER2sYMr5lfwiM2FL0by9EEDuo0xd95wKxZcglamDxwXXSjjimDVYYBKk1zsceJ8Dd9E0kR9P47iEkaPKDyHOSSNVzD3hFXMXWkvzpe/6eS3OcFtRejvE6LMM1qa+aqd2PvvVLDwdEocAmER/+HLw3fDyHfYSX1emzob6z1wRIQmUDKiwQ0j+t0dc8AchDlvkdBbVE0WZJdy8DLpiByyjMfFxst+9pQ+NM6cVGEBzPwZIBYUf/0X9lFx7VUVKHCBgE6FCalaEPouno6q1rUgaEwAXoi+5qgXA06a0fxJRaBGX9OzfRhG151eOmPJR2X7B/lDW9GFTwAQkATq/tMD33rwZzpWSMywwhcDsK/syUccjw3axrLWn54J3hC+0gOyzpCe96zqzaTzdfafYY6/SYwBgATLi/Ukx1/16bk8F6qf7emmgbjAaGDYxkqXGJYUeawvC7ANS7eoOeAbH7OD45bqIy6frfHwbmuA/w004J97U/rXmUxPp4XgTmFAOZW1bgmCea+ZozgkvkyUKK4vJhjNGpRYhBvjFPhau+ASnnlpQhUxfguqfSmyh6gkQgNyQE=
env:
  global:
  - GH_REF: github.com/excaliburjs/ludum-38.git
script:
- chmod ugo+x deploy.sh
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./deploy.sh'
